// Liste des formes juridiques françaises (INPI)
export const LEGAL_FORMS = [
  'SARL — Société à responsabilité limitée',
  'SAS — Société par actions simplifiée',
  'SASU — Société par actions simplifiée unipersonnelle',
  'EURL — Entreprise unipersonnelle à responsabilité limitée',
  'SA — Société anonyme',
  'SNC — Société en nom collectif',
  'SCS — Société en commandite simple',
  'SCA — Société en commandite par actions',
  'SCI — Société civile immobilière',
  'SCOP — Société coopérative',
  'SCIC — Société coopérative d\'intérêt collectif',
  'SEM — Société d\'économie mixte',
  'EARL — Exploitation agricole à responsabilité limitée',
  'GAEC — Groupement agricole d\'exploitation en commun',
  'EI — Entreprise individuelle',
  'EIRL — Entreprise individuelle à responsabilité limitée',
  'Micro-entreprise / Auto-entrepreneur',
  'SARL unipersonnelle',
  'Association (loi 1901)',
  'Établissement public',
  'Autre',
];